version: "3.9"

services:
  api:
    build: .
    volumes:
      - ./src/pyback:/app/app
    environment:
      - POI_DB_URL=postgresql://postgres:postgres@poi-db:5432/test_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8001:80
    restart: always

  db:
    image: postgres
    hostname: poi-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  s3:
    image: zenko/cloudserver
    hostname: s3-server
    ports:
      - 8002:8000
    environment:
      - S3BACKEND=mem
